//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saifmohamed.w4
{
    using System;
    using System.Collections.Generic;
    
    public partial class userr
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string phonenum { get; set; }
        public string city { get; set; }
    }
}
